# Generated by Django 5.1.5 on 2025-06-28 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tools', models.TextField(blank=True, help_text='Comma-separated list of tools')),
                ('projects', models.TextField(blank=True, help_text='Comma-separated list of projects')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('plan', models.CharField(choices=[('Standard', 'Standard Plan'), ('Advanced', 'Advanced Plan')], max_length=20)),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True)),
                ('has_discount', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wev.course')),
            ],
        ),
    ]
