# Generated by Django 5.1.5 on 2025-08-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('Graduated', 'Graduated')], max_length=20)),
                ('college', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
