# Generated by Django 5.2.7 on 2026-02-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programregister',
            name='package',
            field=models.CharField(blank=True, choices=[('ccna', 'CCNA Only'), ('combo', 'CCNA + Ethical Hacking'), ('hacking', 'Ethical Hacking Only')], max_length=20),
        ),
    ]
