# Generated by Django 5.2.7 on 2026-02-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer-not-to-say', 'Prefer not to say')], max_length=20)),
                ('college', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=150)),
                ('year', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('Graduated', 'Graduated'), ('Working', 'Working Professional')], max_length=30)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('service', models.CharField(choices=[('web-development', 'Web Development'), ('mobile-app', 'Mobile App Development'), ('ecommerce', 'E-commerce Solutions'), ('digital-marketing', 'Digital Marketing'), ('seo', 'SEO Services'), ('consulting', 'Technical Consulting')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
